name: Docker Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: arboreal-cosmos-440011-r8
  REGION: asia-southeast2
  REPOSITORY_ID: warung-kopi-dua
  IMAGE_NAME: test-app-akm
  STATUS : berhasil
  SERVICE_NAME: warung-kopi-saja
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan & Apply
      run: |
        terraform plan
        terraform apply -auto-approve

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: |
        docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_ID}/${IMAGE_NAME}:latest .

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_ID}/${IMAGE_NAME}:latest
    - name: Deploy to Cloud Run
      env:  
       REPOSITORY_ID: asia-southeast2-docker.pkg.dev/${{ env.PROJECT_ID }}/warung-kopi-dua

      run: |
          DEPLOY_OUTPUT=$(gcloud run deploy warung-kopi-saja  \
            --image "$REPOSITORY_ID/akmal-app:latest" \
            --platform managed \
            --region asia-southeast2 \
            --port 8080 \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 1 \
            --allow-unauthenticated \
            --project ${{ env.PROJECT_ID  }} \
            --format=json)

    - name: Verify HTTP 200 from Cloud Run
      run: |
        SERVICE_URL=$(gcloud run services describe ${SERVICE_NAME} \
          --platform managed \
          --region ${REGION} \
          --project ${PROJECT_ID} \
          --format='value(status.url)')

        echo "🔍 Checking availability of $SERVICE_URL"

        check_http_200() {
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$1")
            echo "Attempt $i: HTTP status = $STATUS"
            if [[ "$STATUS" == "200" ]]; then
              echo "✅ $1 returned HTTP 200"
              return 0
            fi
            sleep 5
          done
          echo "❌ $1 did not return HTTP 200 after multiple attempts"
          return 1
        }

        check_http_200 "$SERVICE_URL"