name: Docker Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: arboreal-cosmos-440011-r8
  REGION: asia-southeast2
  REPOSITORY_AKM: warung-kopi
  IMAGE_NAME: test-akmal-app
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan & Apply
      run: |
        terraform plan
        terraform apply -auto-approve

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: |
        docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_AKM}/${IMAGE_NAME}:latest .

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_AKM}/${IMAGE_NAME}:latest
    - name: Deploy to Cloud Run
      run: |
          DEPLOY_OUTPUT=$(gcloud run deploy warung-kopi  \
            --image "$REPOSITORY_AKM/test-akmal-app:latest" \
            --platform managed \
            --region asia-southeast2 \
            --port 8080 \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 1 \
            --allow-unauthenticated \
            --project ${{ env.PROJECT_ID  }} \
            --format=json)